### ISSUE TITLE
请教下这个chunk的用处是什么？

### ISSUE THREAD

**Issue by boji123** [YoungSeng/QPGesture#1]
https://github.com/YoungSeng/QPGesture/blob/84127d8b686f94d2343c36034bbbd78220ea2ebf/codebook/models/vqvae.py#L175

**Comment by YoungSeng** [comment]
VQVAE代码参考bailando
看切不切好像是一样的都是一块，可能bailando的训练代码没有切是用这个在时间维度切的吧，这里在训练前已经划分好了
