### ISSUE TITLE
Where is the codebook loss?

### ISSUE THREAD

**Issue by RobinWitch** [YoungSeng/QPGesture#10]
I can find the reconstruction and commit losses as paper mentioned in equation(3), but I can't find the codebook loss anywhere. Could someone point me to where that would be ?

**Comment by YoungSeng** [comment]
Hello, the code of gesture-VQVAE is mainly borrowed from: https://github.com/lisiyao21/Bailando, without any significant changes.

**Comment by RobinWitch** [comment]
Sorry for reply late , emm in this code https://github.com/lisiyao21/Bailando , I still not find where codebook loss is , could you point out for me ?

**Comment by YoungSeng** [comment]
Sorry, I'm using Bailando's code directly, I'm not too sure about the details, you can ask the author of Bailando, good luck.

**Comment by RobinWitch** [comment]
Sorry to bother you , and thank you for your patient reply !

**Comment by huifu99** [comment]
It may be that the EMA is used.
