### ISSUE TITLE
Question about the calculation of evaluation metrics

### ISSUE THREAD

**Issue by YiJin-Chen** [YoungSeng/QPGesture#13]
The three evaluation metrics used in the paper are Hellinger distance average, FGD on feature space, and FGD on raw data space. Could you please provide the pretrained autoencoder for FGD calculation and  the relevant detailed codes for evaluation metrics calculation?

**Comment by YoungSeng** [comment]
Hi, you can refer to the evaluation code here

https://github.com/YoungSeng/ReprGesture#45-evaluation

And please understand that this autoencoder cannot be uploaded in the company's computer.

**Comment by YiJin-Chen** [comment]
Thank you for your reply! I have another question to trouble you.

In the training of codebook and baseline, data from all speakers are used, and the dataset is divided according to the ratio of 8:1:1. Can you tell me the details about the dataset dividing rules? I want to know which motion clips in the BEAT dataset correspond to the train dataset, validation dataset and test dataset.

The experimental results reported in the paper use 4 hours of data from speaker ''Wayne'' and speaker ''Kieks'', which motion clips data from Wayne and Kieks do you use?

**Comment by YoungSeng** [comment]
Hello, the codebook and baseline model are similar to divide the data like this: 

https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/46671fc6af8a3dbcb93cdafca4f07bc064a2c3b1/scripts/twh_dataset_to_lmdb.py#L106

in the motion matching it is the first 100 speeches (if any) of BEAT v0.1 version that are used as a database, and the data after that as a test (ie. 10 kieks 0 103 104, 10 kieks 0 111 112, 1 wayne 0 103 110, 1 wayne 0 111 118).
