### ISSUE TITLE
About the codebook

### ISSUE THREAD

**Issue by huifu99** [YoungSeng/QPGesture#14]
You mentioned that the codebook was constructed based on all speakers. But I only found the code trained on a single speaker. Is there any other codes that are not released?
![image](https://github.com/YoungSeng/QPGesture/assets/115330188/552590f1-99ca-45cb-9cac-bb1ab53d40c4)

**Comment by YoungSeng** [comment]
Yes, only the sample code for speaker 10 is given here, actually the mean, standard deviation of the motions and the actual training is done with all the speakers' motions.

**Comment by huifu99** [comment]
Thanks for reply. Do you plan to release the full training code (including training codebook for all speakers)? Thanks very much.

**Comment by huifu99** [comment]
And is the released codebook (codebook_checkpoint_best.bin) trained on all speakers or a single speaker?

**Comment by YoungSeng** [comment]
Just directly place the other speakers in the BEAT dataset in the same corresponding positions as speaker `1` and `10`. The code itself can iterate through all the data people:

https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/make_beat_dataset.py#L40-L45

(optional) If you want to change the code for the training, validation and test sets, rewriting the code that generates the `lmdb` to traverse all BEAT speakers to train the VQVAE should be easy. And VQVAE trained directly on the training set to overfitting is fine I think. You can refer to [Bailando](https://github.com/lisiyao21/Bailando), [UnifiedGesture](https://github.com/YoungSeng/UnifiedGesture#351-training-vqvae-model) and [End2End](https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/46671fc6af8a3dbcb93cdafca4f07bc064a2c3b1/scripts/twh_dataset_to_lmdb.py#L106) to get more details.

https://github.com/YoungSeng/QPGesture/blob/ef0f2a93f469d7e227896f901c8b1ddda8b2100a/process/beat_data_to_lmdb.py#L176-L179



This pre-trained model is trained on all speakers.
