### ISSUE TITLE
About the normalization

### ISSUE THREAD

**Issue by huifu99** [YoungSeng/QPGesture#15]
It seems that you don't use the normalization during training in lmdb_data_loader.py but use normalization during inference in VisualizeCodebook.py.

**Comment by YoungSeng** [comment]
Thanks for pointing this out, yes I did the normalization ahead of time in the reproduction

https://github.com/YoungSeng/QPGesture/blob/e065e37ee7601a2090ed66d4903b62ccd4381c1a/process/beat_data_to_lmdb.py#L188-L192

 but the readme doesn't make this clear. Normalization can be done in dataloader, I uncommented here. 

https://github.com/YoungSeng/QPGesture/blob/e065e37ee7601a2090ed66d4903b62ccd4381c1a/codebook/data_loader/lmdb_data_loader.py#L64-L66

Sorry for the messy code.
