### ISSUE TITLE
A question about the fps of rotation sequence.

### ISSUE THREAD

**Issue by huifu99** [YoungSeng/QPGesture#19]
You mention that the paper uses rotation sequence of 60fps. Now I want to convert the rotation sequence from 120fps to 100fps, but I meet some error when using 'pymo'. How can I process them? Thanks.

**Comment by YoungSeng** [comment]
Try modifying the `fps` here to 100?

https://github.com/YoungSeng/QPGesture/blob/7dd5daad5c9687e18b8df2282116283fe3f88714/process/beat_data_to_lmdb.py#L32

As well as the audio fps needs to be modified.

Or directly interpolating the processed data with linear interpolation might be useful.

**Comment by huifu99** [comment]
I meet some errors when directly modifying the DownSampler (set fps=100 directly)
https://github.com/YoungSeng/QPGesture/blob/7dd5daad5c9687e18b8df2282116283fe3f88714/process/pymo/preprocessing.py#L1098-L1101

**Comment by YoungSeng** [comment]
Yes, that doesn't seem to support non-integer division sampling, you could try modifying the code in `pymo` that handles `bvh`.
