### ISSUE TITLE
data_processing.py中train_phase = np.load(data_file, allow_pickle=True)['phase']报错

### ISSUE THREAD

**Issue by 912602337** [YoungSeng/QPGesture#2]
报错信息：RuntimeError: Attempting to deserialize object on CUDA device 3 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
请问怎么解决

**Comment by YoungSeng** [comment]
确实是，保存tensor的时候把device也存进去了……要不你先试试有四个GPU的机器，我之后再重新传一下数据集。

**Comment by 912602337** [comment]
> 确实是，保存tensor的时候把device也存进去了……要不你先试试有四个GPU的机器，我之后再重新传一下数据集。

尴尬，就一块卡，😅，

**Comment by YoungSeng** [comment]
你好，已解决cuda问题并处理好了数据库，可见`process/fix_device_bug.py`。你可以重新下载步骤`2 Quick Start`中的数据库进行使用，希望能解决你的问题。
