### ISSUE TITLE
BEAT Datasets

### ISSUE THREAD

**Issue by cyk990422** [YoungSeng/QPGesture#4]
I would like to ask you, does the Euler angle in the BEAT dataset indicate the rotation relative to the parent joint or the rotation relative to the root node?

**Comment by YoungSeng** [comment]
Hi, I think it is relative to the parent node joint, please refer to the baseline of [The GENEA Challenge 2020](https://dl.acm.org/doi/pdf/10.1145/3397481.3450692) and [GENEA 2022](https://dl.acm.org/doi/pdf/10.1145/3536221.3558058), or check its [code](https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/46671fc6af8a3dbcb93cdafca4f07bc064a2c3b1/scripts/twh_dataset_to_lmdb.py#L26).

Help it will help you.
