### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by lihuxiao1** [YoungSeng/QPGesture#7]
Traceback (most recent call last):
  File "make_beat_dataset.py", line 609, in <module>
    make_txt_dataset(save_dir, prefix, mode='noduplication')
  File "make_beat_dataset.py", line 577, in make_txt_dataset
    make_duplication_dataset(key, stride=n_frames)
  File "make_beat_dataset.py", line 571, in make_duplication_dataset
    txt=np.array(txt_data), aux=np.array(aux_data), energy=np.array(energy_data),
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1424,) + inhomogeneous part.

when I generate the speaker_1_state_0_train_240_txt.npz , i can't solve this problem.I guess it's because there was an error generating the file before

**Comment by lihuxiao1** [comment]
![QQ图片20230706160405](https://github.com/YoungSeng/QPGesture/assets/119479418/50a1cdc5-70ec-4ffb-8b5f-e1716b8b9c60)
I adjusted the version of numpy and forcibly generated a txt file，However, when I run GestreKNN, this phase will report an error, and its scale is not consistent with (n * len * 4) in the downloaded file

**Comment by YoungSeng** [comment]
Dear lihuxiao1,

Thank you for catching this problem! 

I changed this [line](https://github.com/YoungSeng/QPGesture/blob/880ceb59f56610ead9ceb202179debac423821d3/codebook/PAE.py#L505) (you need to change it too), plus I updated [this file](https://github.com/YoungSeng/QPGesture/blob/master/process/make_beat_dataset.py) a bit (should not affect your running code), and I upload [a bash](https://github.com/YoungSeng/QPGesture/blob/master/codebook/Speech2GestureMatching/GestureKNN_speaker1_issue.sh) to run quick start; then the detailed process of rebuilding the dataset on speaker `1` is shown [here](https://github.com/YoungSeng/QPGesture/blob/master/dataset/orig_BEAT/readme.md).

Best Regards

**Comment by lihuxiao1** [comment]
> Dear lihuxiao1,
> 
> Thank you for catching this problem!
> 
> I changed this [line](https://github.com/YoungSeng/QPGesture/blob/880ceb59f56610ead9ceb202179debac423821d3/codebook/PAE.py#L505) (you need to change it too), plus I updated [this file](https://github.com/YoungSeng/QPGesture/blob/master/process/make_beat_dataset.py) a bit (should not affect your running code), and I upload [a bash](https://github.com/YoungSeng/QPGesture/blob/master/codebook/Speech2GestureMatching/GestureKNN_speaker1_issue.sh) to run quick start; then the detailed process of rebuilding the dataset on speaker `1` is shown [here](https://github.com/YoungSeng/QPGesture/blob/master/dataset/orig_BEAT/readme.md).
> 
> Best Regards

Thank you very much，I have successfully reproduced it
